hyperskill_project:
  id: 68
  ide_files: https://stepik.org/media/attachments/lesson/219111/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 366
  step: 5790
  is_completed: true
- id: 367
  step: 5791
  is_completed: true
- id: 368
  step: 5792
  is_completed: true
- id: 369
  step: 5793
  is_completed: true
- id: 370
  step: 5794
  is_completed: true
- id: 371
  step: 5795
  is_completed: true
topics:
  0:
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  1:
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Naming variables
    theory_id: 5885
  - title: Taking input
    theory_id: 5913
  - title: Program with numbers
    theory_id: 5872
  - title: Invoking a function
    theory_id: 5891
  - title: Basic data types
    theory_id: 5852
  - title: Integer arithmetic
    theory_id: 5865
  - title: Variables
    theory_id: 5859
  - title: Type casting
    theory_id: 6224
  - title: Basic string methods
    theory_id: 6842
